---
title: "Exercises"
output: html_document
---

Here are some exercises to work on the `max_coverage` functions.

Please provide all code for the answers. This will use the data provided with `maxcovr` - the `york_crime` dataset, and the `york` dataset.

To start, perform the following code, to create the 

# Part A, fixed location

1. Tell me about the existing coverage 

1. Fit the fixed location model, `max_coverage` with `n_added` = 20, 40, 60, 80, 100, and `distance_cutoff = 100`

2. Plot the number of covered users for `n_added` = 20, 40,... to 100.

3. Plot the percentage of covered users for `n_added` = 20 to 100.

4. Plot the mean distance for `n_added` = 20 to 100.

5. Compute the median distance for `n_added` = 20 to 100, and plot.

6. Provide a plot using `leaflet` of the existing AED locations, and the new proposed locations for n = 20, then make individual plots for n = 40, ... up to n = 100.

7. Tell me about the proportion of crimes that are covered - what is the percent coverage for each crime at baseline?

# Part B,  Relocation model

1. Fit the relocation model, `max_coverage_relocation` with:
  - `distance_cutoff = 100`
  - `cost_install = 20`
  - `cost_removal = 5`
  - `cost_total = ` 100, 200, 300, 400, 500.
  - `solver = "gurobi"`

2. Plot the number of covered users for `cost_total` = 100 to 500

3. Plot the percentage of covered users for `cost_total` = 100 to 500

4. Plot the mean distance for for `cost_total` = 100 to 500

5. Compute the median distance for for `cost_total` = 100 to 500, and plot this.

6. Provide a plot using `leaflet` of the existing AED locations, and the new proposed locations for n = 20, then make individual plots for n = 40, ... up to n = 100.

7. Tell me about the proportion of crimes that are covered - what is the percent coverage for each crime at baseline?

# Part C, Cross validation of data

To explore how the optimisation generalises, to new areas, we are going to fit the max coverage model on 80% of the data, and then test it on each of these.

Look at tghe vignette "Cross Validation with Maxcovr", and repeat the above exercises for the fixed location model and the flexible/relocation model (Part A and Part B)

