# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert degrees to radians
#'
#' @param deg degrees
#'
#' @return radians
#'
#' @export
deg2rad_cpp <- function(deg) {
    .Call('maxcovr_deg2rad_cpp', PACKAGE = 'maxcovr', deg)
}

#' Calculate distance using haversines formula
#'
#' @param lat1 latitude from the first location
#' @param long1 longitude from the first location
#' @param lat2 latitude from the second location
#' @param long2 longitude from the second location
#'
#' @return distance in metres between two locations
#'
#' @export
spherical_distance_cpp <- function(lat1, long1, lat2, long2) {
    .Call('maxcovr_spherical_distance_cpp', PACKAGE = 'maxcovr', lat1, long1, lat2, long2)
}

#' Create a matrix of distances between two areas
#'
#' @param facility a matrix with longitude and latitude in the first two columns
#' @param user a matrix with longitude and latitude in the first two columns
#'
#' @return a matrix of distances in metres between each user and facility,
#' with nrow(user) rows and nrow(facility) columns.
#'
#' @export
#'
distance_matrix_cpp <- function(facility, user) {
    .Call('maxcovr_distance_matrix_cpp', PACKAGE = 'maxcovr', facility, user)
}

